const services = [
  {
    name: "生成AI導入支援",
    nameEn: "Generative AI",
    description: "ChatGPT・Claude・Dify・n8nを活用したAIチャットボット構築・業務自動化・ワークフロー設計。社内AIツールの導入から運用定着まで伴走します。",
    color: "#22D3EE",
    rotation: "md:rotate-[-4deg] rotate-0",
  },
  {
    name: "AI企業研修",
    nameEn: "AI Training",
    description: "プロンプトエンジニアリング・ChatGPT活用・生成AI業務応用。現場レベルに合わせた実践型カリキュラムで、全社のAIリテラシーを底上げします。",
    color: "#818CF8",
    rotation: "md:rotate-[4deg] rotate-0",
  },
  {
    name: "SNS・広告支援",
    nameEn: "Social & Ads",
    description: "Instagram・TikTok・X・YouTubeの運用代行からMeta広告・TikTok広告の運用最適化まで。データドリブンな施策でROASを最大化します。",
    color: "#F472B6",
    rotation: "md:rotate-[-4deg] rotate-0",
  },
  {
    name: "LINE・ファネル構築",
    nameEn: "LINE & Funnel",
    description: "公式LINEアカウント設計・ステップ配信・リッチメニュー構築から、集客→育成→購買のファネル全体を設計。顧客接点を最大化します。",
    color: "#34D399",
    rotation: "md:rotate-[4deg] rotate-0",
  },
  {
    name: "プロモーション設計",
    nameEn: "Promotion",
    description: "LP制作・キャンペーン企画・インフルエンサーマーケティング・コンテンツ制作。ブランド認知から購買転換まで一気通貫でプロモーションを設計します。",
    color: "#FB923C",
    rotation: "md:rotate-[-4deg] rotate-0",
  },
];

const stats = [
  { label: "支援企業数", amount: "320", value: 320, decimals: 0, suffix: "+" },
  { label: "SNSフォロワー増加累計", amount: "12", value: 12, decimals: 0, suffix: "M+" },
  { label: "平均広告ROAS", amount: "6.8", value: 6.8, decimals: 1, suffix: "倍" },
  { label: "顧客継続率", amount: "94", value: 94, decimals: 0, suffix: "%" },
];

const caseStudies = [
  {
    title: "飲食チェーン",
    sector: "AI Bot",
    metric: "42%",
    metricLabel: "業務時間削減",
    result: "ChatGPT導入で業務作業時間42%削減",
    detail: "発注・シフト管理・クレーム対応をAIチャットボットで自動化。スタッフの負担を大幅に軽減。",
    bg: "linear-gradient(135deg, #060A0E, #0C1829)",
    rotation: "rotate-z-[-8deg]",
    translation: "translate-y-[-5%]",
  },
  {
    title: "ECサイト",
    sector: "Social Ads",
    metric: "8.4×",
    metricLabel: "広告ROAS達成",
    result: "Meta広告最適化でROAS 8.4倍達成",
    detail: "クリエイティブA/BテストとオーディエンスセグメントをAIで自動最適化。CPAを63%削減。",
    bg: "linear-gradient(135deg, #100614, #0E0A1E)",
    rotation: "rotate-z-[3deg]",
  },
  {
    title: "美容サロン",
    sector: "LINE",
    metric: "8,000",
    metricLabel: "友だち獲得(3ヶ月)",
    result: "LINE公式構築で友だち3ヶ月8,000人増",
    detail: "ステップ配信・クーポン自動送付・予約リマインダーで来店率とリピート率を同時改善。",
    bg: "linear-gradient(135deg, #060C10, #0A1218)",
    rotation: "rotate-z-[-3deg]",
    translation: "translate-y-[-5%]",
  },
  {
    title: "不動産会社",
    sector: "Funnel",
    metric: "3.2×",
    metricLabel: "CVR向上",
    result: "ファネル最適化でCVR 3.2倍達成",
    detail: "広告→LP→LINE登録→商談予約のファネルを全面再設計。各ステップの離脱率を大幅改善。",
    bg: "linear-gradient(135deg, #060A0E, #0A1220)",
    rotation: "rotate-z-[3deg]",
    translation: "translate-y-[5%]",
  },
  {
    title: "SaaS企業",
    sector: "AI Training",
    metric: "92%",
    metricLabel: "AI活用率達成",
    result: "全社AI研修でAI活用率92%に向上",
    detail: "部署別カスタム研修プログラムを設計。Slack/Notionへの生成AI統合で日常業務に定着。",
    bg: "linear-gradient(135deg, #08060E, #0C0A18)",
    rotation: "rotate-z-[-8deg]",
  },
  {
    title: "製造業",
    sector: "Automation",
    metric: "200h",
    metricLabel: "月間自動化達成",
    result: "n8n自動化で月間作業時間200h削減",
    detail: "受発注メール処理・在庫レポート生成・社内QA対応をn8n+AI連携で完全自動化。",
    bg: "linear-gradient(135deg, #060C10, #0A0E18)",
    rotation: "rotate-z-[3deg]",
    translation: "translate-y-[5%]",
  },
  {
    title: "スタートアップ",
    sector: "Promotion",
    metric: "3.8×",
    metricLabel: "ユーザー獲得向上",
    result: "プロモーション設計でユーザー獲得3.8倍",
    detail: "インフルエンサー施策・SNS広告・LP改善を組み合わせたフルファネル施策を展開。",
    bg: "linear-gradient(135deg, #070A18, #0A1018)",
    rotation: "rotate-z-[-2deg]",
    translation: "translate-y-[10%]",
  },
];

export { services, stats, caseStudies };
